buildSrc/src/main/kotlin/DependencyResolution.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
codegen-runtime/build.gradle.kts
codegen-runtime/src/main/kotlin/io/spine/chords/runtime/MessageDef.kt
codegen-runtime/src/main/kotlin/io/spine/chords/runtime/MessageField.kt
codegen-runtime/src/main/kotlin/io/spine/chords/runtime/MessageOneof.kt
codegen-runtime/src/main/kotlin/io/spine/chords/runtime/MessageType.kt
dependencies.md
pom.xml
settings.gradle.kts

This PR adds the `codegen-runtime` module to Chords.
Also, added the `MessageDef` interface for further use in codegen.

Move `codegen-runtime` module from 1DAM

---

dependencies.md
pom.xml
version.gradle.kts

This changeset updates the version to `2.0.0-SNAPSHOT.6` and triggers the publishing, which failed for the previous version.

Update version to `2.0.0-SNAPSHOT.6` and restore publishing

---

codegen-runtime/src/main/kotlin/io/spine/chords/runtime/MessageDef.kt
codegen-runtime/src/main/kotlin/io/spine/chords/runtime/ValidatingBuilderExts.kt
dependencies.md
pom.xml

This PR adds an extension to `ValidatingBuilder` that allows reading the `messageDef` property generated for the message builder.

Implement extension for `ValidatingBuilder` that returns the implementation of `MessageDef`

---

codegen-plugins/buildSrc/src/main/kotlin/io/spine/internal/dependency/Chords.kt
codegen-plugins/message-fields/src/main/kotlin/io/spine/chords/protodata/plugin/MessageDefFileGenerator.kt
codegen-plugins/message-fields/src/main/kotlin/io/spine/chords/protodata/plugin/MessageFieldsRenderer.kt

This PR includes migration to the latest version of `codegen-runtime`.
The `MessageDef.MESSAGE_DEF_CLASS_SUFFIX` constant is used in code generation.

Migrate to newer version of `codegen-runtime`

---

build.gradle.kts
buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/CheckVersionIncrement.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/ChordsPublishing.kt
dependencies.md
pom.xml
version.gradle.kts

This PR fixes the version increment check. Actually, fixed the module prefix when fetching the metadata of the remote Maven repository while checking for the versions already published.
Also, the increment version check is disabled for the root module.
P.S. Added constant for artifact prefix for publishing/reading artifacts to/from repositories.

Fix version increment check

---

README.md
client/README.md
client/build.gradle.kts
client/src/main/kotlin/io/spine/chords/Client.kt
client/src/main/kotlin/io/spine/chords/DesktopClient.kt
client/src/main/kotlin/io/spine/chords/EntityChooser.kt
client/src/main/kotlin/io/spine/chords/appshell/ClientApplication.kt
client/src/main/kotlin/io/spine/chords/form/CommandMessageForm.kt
client/src/main/kotlin/io/spine/chords/layout/CommandWizard.kt
client/src/main/kotlin/io/spine/chords/person/UserChooser.kt
dependencies.md
pom.xml
version.gradle.kts

Adds the Chords Client library (residing in the `client` module), which complements the other libraries with components that support server connectivity using the Spine Event Engine.

Add `client` module

---

buildSrc/src/main/kotlin/jvm-module.gradle.kts
dependencies.md
pom.xml
version.gradle.kts

This PR removes the redundant `spine-logging` dependency, which belongs to the Spine 2.0 ecosystem, while the Chords libs themselves are based on Spine 1.9.
The presence of `spine-logging` was apparently causing a conflict in the downstream project, hence this is also an experiment to see whether this update might fix that issue.

Remove the `spine-logging` dependency

---

dependencies.md
pom.xml
proto-values/src/main/kotlin/io/spine/chords/proto/value/protobuf/MessageExts.kt
proto-values/src/main/kotlin/io/spine/chords/proto/value/time/TimeExts.kt
proto/src/main/kotlin/io/spine/chords/proto/form/MessageForm.kt
proto/src/main/kotlin/io/spine/chords/proto/money/PaymentMethodEditor.kt
proto/src/main/kotlin/io/spine/chords/proto/time/DateText.kt
proto/src/main/kotlin/io/spine/chords/proto/time/DateTimeField.kt
version.gradle.kts

This PR does the following:
- Replaces remaining usages of Protobuf reflection with `MessageDef` API
- Replaces `KClass`-based message refs with `MessageDef`-based ones.
- Moves the `TimeExts.kt` file to the Chords Proto Values library where it should belong.

Adopt the new `MessageDef`s API

---

.github/workflows/publish.yml
dependencies.md
pom.xml
version.gradle.kts

This PR fixes the `publish` action by specifying the absolute path to credentials file instead of the relative one.

Fix "publish" action by specifying the absolute path to credentials file

---

.github/workflows/publish.yml
dependencies.md
pom.xml
version.gradle.kts

This PR excludes `updateGitHubPages` Gradle task from the publishing script.

Exclude `updateGitHubPages` Gradle task from publishing

---

client/src/main/kotlin/io/spine/chords/client/Client.kt
client/src/main/kotlin/io/spine/chords/client/DesktopClient.kt
codegen/gradle-plugin/build.gradle.kts
dependencies.md
pom.xml
version.gradle.kts

This PR extends the `Client` API to allow reading entities by ID from the application read side.
Also, as of this PR we temporarily disable the publication of Chords Gradle plugin to the Gradle plugin portal, since it still lacks the documentation, and therefore, wasn't approved by the Gradle team.

Extend the `Client` API to allow reading entities by ID

---

.gitmodules
build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
codegen/gradle-plugin/build.gradle.kts
codegen/tests/build.gradle.kts
dependencies.md
pom.xml
proto-values/build.gradle.kts
settings.gradle.kts
version.gradle.kts

This PR adds the use of the Gradle plugin for code generation.
Also, the `codegen/workspace` module has been removed as it is no longer needed.

Use Gradle plugin for code generation

---

core/src/main/kotlin/io/spine/chords/core/appshell/AppWindow.kt
core/src/main/kotlin/io/spine/chords/core/appshell/Application.kt
core/src/main/kotlin/io/spine/chords/core/modal/ModalWindow.kt
dependencies.md
pom.xml
version.gradle.kts

This PR implements the `ModalWindow` component and extends the API of the `AppWindow` class allowing the creation and management of modal dialogs within the application.

Implement the modal window functionality 

---

.github/workflows/build-on-ubuntu.yml
.github/workflows/build-on-windows.yml
.github/workflows/ensure-reports-updated.yml
.github/workflows/gradle-wrapper-validation.yml
.github/workflows/increment-guard.yml
core/src/main/kotlin/io/spine/chords/core/appshell/AppWindow.kt
dependencies.md
pom.xml
version.gradle.kts

This PR resolves a regression introduced in PR #48 that prevented modal screens from displaying, restoring expected functionality. Also, this PR adds the concurrency control setting to GitHub workflows to prevent overlapping runs.

Resolve the modal screen display issue

---

codegen/plugins/codegen-plugins/src/main/kotlin/io/spine/chords/codegen/plugins/MessageDefFileGenerator.kt
codegen/plugins/codegen-plugins/src/main/kotlin/io/spine/chords/codegen/plugins/MessageDefObjectGenerator.kt
codegen/plugins/codegen-plugins/src/main/kotlin/io/spine/chords/codegen/plugins/MessageOneofObjectGenerator.kt
codegen/runtime/src/main/kotlin/io/spine/chords/runtime/MessageDef.kt
codegen/runtime/src/main/kotlin/io/spine/chords/runtime/MessageOneof.kt
dependencies.md
pom.xml
version.gradle.kts

This PR removes `out` modifiers from the generic parameters of `MessageOneof` and `MessageDef` interfaces.
Otherwise, it leads to unnecessary type casts. See [this issue](https://github.com/SpineEventEngine/Chords/issues/38) for detail.

Remove `out` modifiers from the generic parameters of `codegen-runtime` interfaces

---

client/src/main/kotlin/io/spine/chords/client/form/CommandMessageForm.kt
client/src/main/kotlin/io/spine/chords/client/layout/CommandWizard.kt
dependencies.md
pom.xml
proto/src/main/kotlin/io/spine/chords/proto/form/MessageForm.kt
version.gradle.kts

This PR enhances the `CommandMessageForm` component creation by using the invoke operator. It adds a parameter that allows to programmatically amend the message before the form is submitted.

Extend API for creating the `CommandMessageForm` component

---

buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
codegen/plugins/build.gradle.kts
codegen/plugins/buildSrc/src/main/kotlin/BuildExtensions.kt
codegen/plugins/buildSrc/src/main/kotlin/io/spine/internal/dependency/McJava.kt
codegen/plugins/buildSrc/src/main/kotlin/io/spine/internal/dependency/ProtoData.kt
codegen/plugins/buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
codegen/plugins/codegen-plugins/build.gradle.kts
codegen/plugins/codegen-plugins/src/main/kotlin/io/spine/chords/codegen/plugins/BuilderExtensionGenerator.kt
codegen/plugins/codegen-plugins/src/main/kotlin/io/spine/chords/codegen/plugins/FieldView.kt
codegen/plugins/codegen-plugins/src/main/kotlin/io/spine/chords/codegen/plugins/KClassPropertiesGenerator.kt
codegen/plugins/codegen-plugins/src/main/kotlin/io/spine/chords/codegen/plugins/MessageDefFileGenerator.kt
codegen/plugins/codegen-plugins/src/main/kotlin/io/spine/chords/codegen/plugins/MessageDefObjectGenerator.kt
codegen/plugins/codegen-plugins/src/main/kotlin/io/spine/chords/codegen/plugins/MessageFieldObjectGenerator.kt
codegen/plugins/codegen-plugins/src/main/kotlin/io/spine/chords/codegen/plugins/MessageFieldsPlugin.kt
codegen/plugins/codegen-plugins/src/main/kotlin/io/spine/chords/codegen/plugins/MessageFieldsRenderer.kt
codegen/plugins/codegen-plugins/src/main/kotlin/io/spine/chords/codegen/plugins/MessageOneofObjectGenerator.kt
codegen/plugins/codegen-plugins/src/main/resources/codegen-workspace/build.gradle.kts
dependencies.md
pom.xml
version.gradle.kts

This PR migrates the projects to the latest versions of Chords Gradle plugin `(1.9.10)` and ProtoData `(0.61.7)`.

Migrate to the latest versions of Chords Gradle plugin and ProtoData

---

codegen/plugins/codegen-plugins/src/main/kotlin/io/spine/chords/codegen/plugins/MessageDefObjectGenerator.kt
codegen/plugins/codegen-plugins/src/main/kotlin/io/spine/chords/codegen/plugins/MessageFieldObjectGenerator.kt
codegen/plugins/codegen-plugins/src/main/kotlin/io/spine/chords/codegen/plugins/MessageOneofObjectGenerator.kt
codegen/runtime/src/main/kotlin/io/spine/chords/runtime/AnyExts.kt
codegen/runtime/src/main/kotlin/io/spine/chords/runtime/MessageOneof.kt
codegen/tests/src/test/kotlin/io/spine/chords/codegen/CodegenPluginsSpec.kt
codegen/tests/src/test/proto/spine/chords/codegen/commands.proto
dependencies.md
pom.xml
version.gradle.kts

This PR updates codegen plugins with the following improvements:
- `Any.safeCast` throws an exception instead of returning `null` so there is no need to use the operator `!!` in the client's code.
- Add the `required` property to `MessageOneof` and generate the appropriate code for the implementations.

Update codegen plugins

---

client/src/main/kotlin/io/spine/chords/client/form/CommandMessageForm.kt
core/src/main/kotlin/io/spine/chords/core/InputComponent.kt
dependencies.md
pom.xml
proto/src/main/kotlin/io/spine/chords/proto/form/MessageForm.kt
proto/src/main/kotlin/io/spine/chords/proto/form/MessageFormScopes.kt
proto/src/main/kotlin/io/spine/chords/proto/money/PaymentMethodEditor.kt
version.gradle.kts

This PR:
- Introduces an ability to create custom form implementations for specific data types with built-in content.
- Reworks `PaymentMethodEditor` to be such a custom form, while ensuring that it can be used as an editor for both a required and optional fields (the respective checkbox is either visible or not in this case).
- Updates the KDoc format for some form-related declarations.

Rework `PaymentMethodEditor` to be a class-based custom form component

---

client/src/main/kotlin/io/spine/chords/client/form/CommandMessageForm.kt
client/src/main/kotlin/io/spine/chords/client/layout/CommandWizard.kt
dependencies.md
pom.xml
proto/src/main/kotlin/io/spine/chords/proto/form/MessageForm.kt
version.gradle.kts

This PR revises the signature of the `onBeforeBuild` callback for `MessageForm`/`CommandMessageForm` by removing a redundant return value. 
The reasons for for considering it excessive are the following:
- The main reason is that there's nothing to return in general for this callback in the first place. There's one-way flow of data _into_ the function both logically and technically in this case.
- If it's there when it's not needed, having it in the signature is confusing from several perspectives:
- From the user's perspective: this signature alone provokes the thought that the builder's instance that is returned might be (or even might have to be?) different than that, which is passed as the parameter.
- From the perspective of developer/maintainer of `MessageForm` itself this provokes …

Remove redundant return value from the `onBeforeBuild` callback 

---

core/src/main/kotlin/io/spine/chords/core/appshell/AppWindow.kt
core/src/main/kotlin/io/spine/chords/core/appshell/NavigationDrawer.kt
core/src/main/kotlin/io/spine/chords/core/appshell/TopBar.kt
dependencies.md
pom.xml
version.gradle.kts

This PR updates the application’s background color to align with the `MaterialTheme.colorScheme.background` role. By setting the background color to this theme attribute, the default app view will better adhere to the Material Design guidelines.

Use `MaterialTheme.colorScheme.background` for application background color

---

client/src/main/kotlin/io/spine/chords/client/form/CommandMessageForm.kt
client/src/main/kotlin/io/spine/chords/client/layout/CommandWizard.kt
core/src/main/kotlin/io/spine/chords/core/Component.kt
core/src/main/kotlin/io/spine/chords/core/DropdownListBox.kt
dependencies.md
pom.xml
proto/src/main/kotlin/io/spine/chords/proto/form/InputComponentExt.kt
proto/src/main/kotlin/io/spine/chords/proto/form/MessageForm.kt
proto/src/main/kotlin/io/spine/chords/proto/form/MessageFormCompanion.kt
proto/src/main/kotlin/io/spine/chords/proto/form/MessageFormDeclarationApi.kt
proto/src/main/kotlin/io/spine/chords/proto/form/MessageFormScopes.kt
proto/src/main/kotlin/io/spine/chords/proto/form/MessageFormSetup.kt
proto/src/main/kotlin/io/spine/chords/proto/form/OneofRadioButton.kt
proto/src/main/kotlin/io/spine/chords/proto/money/BankAccountField.kt
proto/src/main/kotlin/io/spine/chords/proto/money/MoneyField.kt
proto/src/main/kotlin/io/spine/chords/proto/money/PaymentCardNumberField.kt
proto/src/main/kotlin/io/spine/chords/proto/money/PaymentMethodEditor.kt
proto/src/main/kotlin/io/spine/chords/proto/net/EmailField.kt
proto/src/main/kotlin/io/spine/chords/proto/net/InternetDomainField.kt
proto/src/main/kotlin/io/spine/chords/proto/net/IpAddressField.kt
proto/src/main/kotlin/io/spine/chords/proto/net/UrlField.kt
proto/src/main/kotlin/io/spine/chords/proto/people/PersonNameField.kt
proto/src/main/kotlin/io/spine/chords/proto/time/DateTimeField.kt
version.gradle.kts

This PR includes:
- Adds a missing companion object for `PaymentMethodEditor`, which is required to declare instances of this component.
- Renames the parent class for component companions from `ComponentCompanion` to `ComponentSetup` (and renames all other respective classes in this hierarchy accordingly).
- Introduces the `MessageFormSetup` class for creating companion objects of custom `MessageForm` implementations (similar to `PaymentMethodEditor`), and reworks companion objects of `MessageForm` and `CommandMessageForm` to reuse respective code with it.
- Revises the documentation of `Component` and its related companion classes to elaborate on the notion and usage of companion objects of class-based components.
- Makes companion object definitions in existing class-based components …

Revise definitions of component's companion objects, add companion object for `PaymentMethodEditor`

---

build.gradle.kts
dependencies.md
pom.xml
version.gradle.kts

Publishing sometimes fails for modules that rely on code generation because `codegen-plugins` project has not yet been published.
A dependency on the `codegenPluginsPublish` task was set at the root project level; however, it did not ensure that this task would be executed before publishing certain subprojects.
Root `build.gradle.kts`:
```
tasks.named("publish") {
dependsOn(codegenPluginsPublish)
}
```
A direct dependency on the `codegenPluginsPublish` task was added for projects that require code generation.

Fix dependency on `codegenPluginsPublish` task for modules that require code generation

---

build.gradle.kts
dependencies.md
pom.xml
version.gradle.kts

This PR fixes the dependency on `codegen-plugins` publishing.
The long story is described in the previous [PR](https://github.com/SpineEventEngine/Chords/pull/75).
@armiol You were right. It was an overkill and it did not fix the problem...
The real problem is related to the work of the Chords Gradle plugin in the context of Chords build. Actually, the plugin executes three tasks in a row
1. `createCodegenWorkspace` 
2. `addGradleWrapperRunPermission` 
3. `applyCodegenPlugins`
and the required dependency for publishing of `codegen-plugins` was set for the last task. This setup worked well as long as the plugin contained the files necessary for creating the `codegen-workspace` within its resources. However, once the plugin started reading resources from the `codegen-plugins` artifact, the …

Add the correct dependency on `codegen-plugins` publishing

---

.idea/inspectionProfiles/Project_Default.xml
core/src/main/kotlin/io/spine/chords/core/Component.kt
core/src/main/kotlin/io/spine/chords/core/appshell/AppWindow.kt
core/src/main/kotlin/io/spine/chords/core/appshell/Application.kt
core/src/main/kotlin/io/spine/chords/core/layout/ConfirmationDialog.kt
core/src/main/kotlin/io/spine/chords/core/layout/Dialog.kt
dependencies.md
pom.xml
proto/src/main/kotlin/io/spine/chords/proto/form/MessageForm.kt
proto/src/main/kotlin/io/spine/chords/proto/money/PaymentMethodEditor.kt
version.gradle.kts

`ConfirmCancellationDialog` extends `Dialog`, but so far it still used its special mechanism of its displaying because displaying nested `Dialog` components were technically not supported yet.
This PR does the following:
- Makes it possible to display arbitrary nested dialogs while retaining the simplicity of dialog implementations (no special per-dialog code is needed for this).
This does not change the API of using the dialogs. It's just now possible to open dialogs recursively.
- Update `ConfirmCancellationDialog` to be a regular dialog, and still be displayed as a nested one like it is now. It has a custom companion object to introduce a convenient confirmation-specific usage API.
- The specialized `ConfirmCancellationDialog` was replaced with a generic `ConfirmationDialog`, which can …

Support nested dialogs, use them for confirmations

---

core/src/main/kotlin/io/spine/chords/core/layout/ConfirmationDialog.kt
core/src/main/kotlin/io/spine/chords/core/layout/Dialog.kt
dependencies.md
pom.xml
version.gradle.kts

This PR:
- Makes it possible to display dialogs as desktop windows.
- Still retains the possibility of using the previously supported way of displaying dialogs as lightweight popups. The way how the dialog is dipslayed can be chosen using the `displayMode` property.

Add support for displaying dialogs in separate windows

---

core/src/main/kotlin/io/spine/chords/core/Component.kt
core/src/main/kotlin/io/spine/chords/core/appshell/Application.kt
core/src/main/kotlin/io/spine/chords/core/appshell/ComponentDefaults.kt
core/src/main/kotlin/io/spine/chords/core/layout/ConfirmationDialog.kt
core/src/main/kotlin/io/spine/chords/core/layout/Dialog.kt
dependencies.md
pom.xml
version.gradle.kts

This PR adds an ability to specify default property values for arbitrary component types on an application-wide basis.
See the `Application` class's KDocs for the description of this functionality.

Application-wide components customization

---

client/src/main/kotlin/io/spine/chords/client/form/CommandMessageForm.kt
client/src/main/kotlin/io/spine/chords/client/layout/CommandDialog.kt
client/src/main/kotlin/io/spine/chords/client/layout/CommandWizard.kt
core/src/main/kotlin/io/spine/chords/core/Delegates.kt
core/src/main/kotlin/io/spine/chords/core/DropdownListBox.kt
core/src/main/kotlin/io/spine/chords/core/DropdownSelector.kt
core/src/main/kotlin/io/spine/chords/core/FocusableComponent.kt
core/src/main/kotlin/io/spine/chords/core/InputComponent.kt
core/src/main/kotlin/io/spine/chords/core/InputField.kt
core/src/main/kotlin/io/spine/chords/core/layout/Dialog.kt
core/src/main/kotlin/io/spine/chords/core/layout/Wizard.kt
core/src/main/kotlin/io/spine/chords/core/primitive/CheckboxWithText.kt
core/src/main/kotlin/io/spine/chords/core/primitive/RadioButtonWithText.kt
dependencies.md
pom.xml
proto/src/main/kotlin/io/spine/chords/proto/form/CheckBoxWithTextExt.kt
proto/src/main/kotlin/io/spine/chords/proto/form/InputComponentExt.kt
proto/src/main/kotlin/io/spine/chords/proto/form/MessageForm.kt
proto/src/main/kotlin/io/spine/chords/proto/form/MessageFormScopes.kt
proto/src/main/kotlin/io/spine/chords/proto/form/MessageFormSetupBase.kt
proto/src/main/kotlin/io/spine/chords/proto/form/OneofRadioButton.kt
proto/src/main/kotlin/io/spine/chords/proto/form/OptionalMessageCheckbox.kt
proto/src/main/kotlin/io/spine/chords/proto/money/MoneyField.kt
proto/src/main/kotlin/io/spine/chords/proto/money/PaymentMethodEditor.kt
version.gradle.kts

This PR introduces the functionality of disabling field editors inside `CommandForm` when the command posted by the form is being handled (until the completion event or until the respective timeout period elapses).
Besides, the PR contains the following:
- Adds the `enabled` property to `InputComponent` and ensures that implementations support it.
- Corrected disabling of `DropdownSelector` so that it can't be opened when in the disabled state and its buttons are not highlighted on hovering.
- Made `CheckboxWithText` to pick up the form's `editorsEnabled` state from the context as well.
- Made submission buttons of `CommandDialog` and `CommandWizard` to be disabled while the command is being posted.
- Other misc. corrections that were made along the way:
- Fixed focusing the form if the …

Support disabling `CommandForm` during posting

---

client/src/main/kotlin/io/spine/chords/client/Client.kt
client/src/main/kotlin/io/spine/chords/client/DesktopClient.kt
client/src/main/kotlin/io/spine/chords/client/form/CommandMessageForm.kt
client/src/main/kotlin/io/spine/chords/client/layout/CommandDialog.kt
core/src/main/kotlin/io/spine/chords/core/Component.kt
core/src/main/kotlin/io/spine/chords/core/Delegates.kt
core/src/main/kotlin/io/spine/chords/core/DropdownListBox.kt
core/src/main/kotlin/io/spine/chords/core/InputComponent.kt
core/src/main/kotlin/io/spine/chords/core/appshell/Application.kt
core/src/main/kotlin/io/spine/chords/core/layout/ConfirmationDialog.kt
core/src/main/kotlin/io/spine/chords/core/layout/Dialog.kt
core/src/main/kotlin/io/spine/chords/core/layout/MessageDialog.kt
core/src/main/kotlin/io/spine/chords/core/layout/SubmitOrCancelDialog.kt
dependencies.md
pom.xml
proto/src/main/kotlin/io/spine/chords/proto/form/CustomMessageForm.kt
proto/src/main/kotlin/io/spine/chords/proto/form/MessageForm.kt
version.gradle.kts

This PR:
* Introduces a basic notion of `CommandOutcomeHandler`, which works together with `CommandMessageForm`, and for now is mainly responsible for handling the command posting outcome waiting timeout. The default implementation (`DefaultOutcomeHandler`) displays a message dialog in this situation.
* Introduces the `MessageDialog` component, which provides an easy way of displaying a simple dialog that presents the provided text message to the user.
* Makes the implementation of `Dialog` a bit more generic to support different number of buttons, and introduce a `SubmitOrCancel` dialog as a base class for Submit/Cancel type of dialogs.
* Extends KDocs a bit, including the component's lifecycle description in `Component`'s KDocs in particular.

Handle command reaction timeout in `CommandMessageForm`

---

codegen/plugins/buildSrc/src/main/kotlin/io/spine/dependency/local/Base.kt
dependencies.md
pom.xml
version.gradle.kts

This PR updates the `Spine-base` dependency version to `2.0.0-SNAPSHOT.234`.

Update version of `Spine-base` dependency

---

core/src/main/kotlin/io/spine/chords/core/appshell/AppWindow.kt
core/src/main/kotlin/io/spine/chords/core/appshell/Application.kt
dependencies.md
pom.xml
version.gradle.kts

This PR introduces a navigation shortcut that allows the application to switch to the sign-in screen from any place.
This implementation serves as a straightforward solution to meet the current needs of the 1DAM application. In the future, it should be considered to implement a more comprehensive navigation API to enable seamless navigation to any screen within the app.

Add navigation shortcut to switch to the sign-in screen

---

client/src/main/kotlin/io/spine/chords/client/Client.kt
client/src/main/kotlin/io/spine/chords/client/CommandConsequences.kt
client/src/main/kotlin/io/spine/chords/client/DesktopClient.kt
client/src/main/kotlin/io/spine/chords/client/layout/ModalCommandConsequences.kt
core/src/main/kotlin/io/spine/chords/core/layout/ConfirmationDialog.kt
core/src/main/kotlin/io/spine/chords/core/layout/MessageDialog.kt
dependencies.md
pom.xml
version.gradle.kts

This PR includes the following:
- Correct the capability to customize `CommandConsequences.defaultTimeout` property.
- Fix the timeout callback's coroutine scope to be active when the callback is invoked (which fixes complex scenarios within a callback, such as closing a dialog after showing a message).
- Move making event subscriptions (which are relatively time-consuming) after `onBeforePost` callbacks to improve the UX of posting progress display.
- Offload the server communication operations (making subscriptions, posting of a command) to the IO coroutine dispatcher to ensure timely UI updates within consequence callbacks (especially actual for `onBeforePost`).
- Minor KDoc and code style corrections.

Fix some command consequences related issues

---

core/src/main/kotlin/io/spine/chords/core/table/Table.kt
dependencies.md
pom.xml
version.gradle.kts

This PR includes the following:
- The `selectedEntity` property of `Table` is now mutable, which is convenient when the app needs to maintain selection in its own `MutableState` instance.
- Since `Table` preserves its selection by entity's identifier, it's possible that an updated `entities` list will contain a new version of the selected entity. This PR ensures that the `selectedEntity` state gets an up-to-date value of the selected entity in such cases now.
- The `handleRowClick` method is no longer abstract. There's no need to force-implement it now because just specifying `selectedEntity` can be enough.

Improve table selection handling

---

build.gradle.kts
buildSrc/src/main/kotlin/io/spine/internal/dependency/KotlinX.kt
client/build.gradle.kts
client/src/main/kotlin/io/spine/chords/client/Client.kt
client/src/main/kotlin/io/spine/chords/client/DesktopClient.kt
client/src/main/kotlin/io/spine/chords/client/EntityChooser.kt
client/src/main/kotlin/io/spine/chords/client/layout/ModalCommandConsequences.kt
core/src/main/kotlin/io/spine/chords/core/DropdownListBox.kt
core/src/main/kotlin/io/spine/chords/core/DropdownSelector.kt
core/src/main/kotlin/io/spine/chords/core/appshell/Application.kt
core/src/main/kotlin/io/spine/chords/core/layout/ConfirmationDialog.kt
core/src/main/kotlin/io/spine/chords/core/layout/MessageDialog.kt
dependencies.md
pom.xml
version.gradle.kts

This PR contains the following:
- A fix for the `DropdownListBox`'s item filtering behavior (a regression where items were not filtered automatically until changing the selected item).
- An improvement of the `Client's` API for reading and observing entities:
- The `Client.readAndObserve` method was changed from accepting `MutableState` to creating and returning it automatically, which simplifies its usages.
- Added `Client.readOneAndObserve` to address a common scenario when just one entity state needs to be obtained.
- Speed up closing of main window when existing.
- Added `kotlinx-coroutines-swing` dependency, which is required for `Dispatchers.Main` to be usable.

Fix dropdown filtering, improve `Client` API, other improvements

---

client/src/main/kotlin/io/spine/chords/client/form/CommandMessageForm.kt
core/src/main/kotlin/io/spine/chords/core/Component.kt
core/src/main/kotlin/io/spine/chords/core/DropdownListBox.kt
core/src/main/kotlin/io/spine/chords/core/InputComponent.kt
core/src/main/kotlin/io/spine/chords/core/InputField.kt
core/src/main/kotlin/io/spine/chords/core/layout/Dialog.kt
core/src/main/kotlin/io/spine/chords/core/layout/Wizard.kt
core/src/main/kotlin/io/spine/chords/core/primitive/StringField.kt
dependencies.md
pom.xml
proto/src/main/kotlin/io/spine/chords/proto/form/MessageForm.kt
proto/src/main/kotlin/io/spine/chords/proto/time/DateTimeField.kt
version.gradle.kts

This PR includes the following:
- Implemented `StringField` component (an implementation of `InputField` for editing string-typed fields).
- Added `Component.launch()` method, which simplifies a common need of launching coroutines from components (no explicit invocation of `rememberCoroutineScope()` is required now).
- Cleaned up the code a bit — `CommandMessage.postCommand` doesn't need to be a `suspend` function now.

Implement `StringField` component

---

core/src/main/kotlin/io/spine/chords/core/table/Table.kt
dependencies.md
pom.xml
proto/src/main/kotlin/io/spine/chords/proto/time/DateTimeText.kt
version.gradle.kts

This PR adds support for additional style properties in the `DateText` component.
It also copies the `DateTimeText` component from 1DAM.
Additionally, this PR makes the `Table.columns` a mutable property instead of an abstract read-only one.

Add support for some style properties in `DateText` component

---

core/src/main/kotlin/io/spine/chords/core/table/Table.kt
dependencies.md
pom.xml
version.gradle.kts

This PR makes `Table.columns` public, making it a part of the component's public API.

Make `Table.columns` public

---

client/src/main/kotlin/io/spine/chords/client/form/CommandMessageForm.kt
client/src/main/kotlin/io/spine/chords/client/layout/CommandDialog.kt
client/src/main/kotlin/io/spine/chords/client/layout/CommandWizard.kt
core/src/main/kotlin/io/spine/chords/core/Component.kt
core/src/main/kotlin/io/spine/chords/core/DropdownSelector.kt
core/src/main/kotlin/io/spine/chords/core/InputComponent.kt
core/src/main/kotlin/io/spine/chords/core/InputField.kt
dependencies.md
pom.xml
proto/src/main/kotlin/io/spine/chords/proto/form/InputComponentExt.kt
proto/src/main/kotlin/io/spine/chords/proto/form/MessageForm.kt
proto/src/main/kotlin/io/spine/chords/proto/form/OptionalMessageCheckbox.kt
proto/src/main/kotlin/io/spine/chords/proto/money/MoneyField.kt
proto/src/main/kotlin/io/spine/chords/proto/money/PaymentMethodEditor.kt
version.gradle.kts

This PR revises the names of value-related properties in input components like this with the purpose of making the API more concise like this:
- `InputComponent.valueValid` -> `valid`
- `InputComponent.valueRequired` -> `required`
- `InputField.onValueChange` -> `onChange`
- `InputField.onValidateValue` -> `onValidate`
This PR addresses concerns raised in [this comment](https://github.com/SpineEventEngine/Chords/pull/107#discussion_r2017371965) of PR https://github.com/SpineEventEngine/Chords/pull/107.

Revise property names for input components

---

core/src/main/kotlin/io/spine/chords/core/InputField.kt
dependencies.md
pom.xml
proto/src/main/kotlin/io/spine/chords/proto/form/MessageForm.kt
proto/src/main/kotlin/io/spine/chords/proto/money/MoneyField.kt
proto/src/main/kotlin/io/spine/chords/proto/net/IpAddressField.kt
proto/src/main/kotlin/io/spine/chords/proto/time/DateTimeField.kt
version.gradle.kts

This PR just performs some basic refactoring to simplify the code of `InputReviser` declarations. It covers only basic code simplifications without making substantial revisions, and it does not change the functionality.

Simplify `InputReviser`-related code

---

core/src/main/kotlin/io/spine/chords/core/table/Table.kt
dependencies.md
pom.xml
version.gradle.kts

This PR updates the `Table` component to hide the "More" button when no actions are available for an entity displayed in a row. Previously, the button was shown even when there were no actions, causing unnecessary UI clutter. Additionally, clicking the button in such cases shifted focus to itself, requiring the user to click outside before interacting with other parts of the application.

Hide the "More" button in table rows when no actions are available

---

codegen/plugins/build.gradle.kts
codegen/plugins/buildSrc/src/main/kotlin/io/spine/dependency/local/Base.kt
codegen/plugins/buildSrc/src/main/kotlin/io/spine/dependency/local/CoreJava.kt
codegen/plugins/buildSrc/src/main/kotlin/io/spine/dependency/local/McJava.kt
codegen/plugins/buildSrc/src/main/kotlin/io/spine/dependency/local/ProtoData.kt
codegen/plugins/buildSrc/src/main/kotlin/io/spine/dependency/local/ToolBase.kt
codegen/plugins/buildSrc/src/main/kotlin/io/spine/dependency/local/Validation.kt
codegen/plugins/codegen-plugins/src/main/kotlin/io/spine/chords/codegen/plugins/MessageFieldsRenderer.kt
codegen/plugins/codegen-plugins/src/main/kotlin/io/spine/chords/codegen/plugins/MessageViewRepository.kt
codegen/plugins/codegen-plugins/src/main/resources/codegen-workspace/build.gradle.kts
dependencies.md
pom.xml
version.gradle.kts

This PR updates the code generation plugins to use the newer version of ProtoData `0.92.11`, while continuing to use Java 11 and Gradle 7.6.

Update the codegen plugins to use the newer version of ProtoData `0.92.11`
